var annotated_dup =
[
    [ "base_obj", "structbase__obj.html", "structbase__obj" ],
    [ "base_vtable", "structbase__vtable.html", "structbase__vtable" ],
    [ "broker", "structbroker.html", "structbroker" ],
    [ "Broker_Queue_t", "struct_broker___queue__t.html", "struct_broker___queue__t" ],
    [ "can_obj_t", "structcan__obj__t.html", "structcan__obj__t" ],
    [ "can_timeout_entry_t", "structcan__timeout__entry__t.html", "structcan__timeout__entry__t" ],
    [ "event", "structevent.html", "structevent" ],
    [ "fsm", "structfsm.html", "structfsm" ],
    [ "hw_info_t", "structhw__info__t.html", "structhw__info__t" ],
    [ "message_frame_t", "structmessage__frame__t.html", "structmessage__frame__t" ],
    [ "Metadata_t", "struct_metadata__t.html", "struct_metadata__t" ],
    [ "state", "structstate.html", "structstate" ],
    [ "sw_info_t", "structsw__info__t.html", "structsw__info__t" ],
    [ "sys_id_t", "structsys__id__t.html", "structsys__id__t" ],
    [ "sys_info_t", "structsys__info__t.html", "structsys__info__t" ],
    [ "system_obj_t", "structsystem__obj__t.html", "structsystem__obj__t" ],
    [ "timer_callback_entry", "structtimer__callback__entry.html", "structtimer__callback__entry" ],
    [ "timer_manager_t", "structtimer__manager__t.html", "structtimer__manager__t" ],
    [ "timers_t", "structtimers__t.html", "structtimers__t" ],
    [ "topic_config_t", "structtopic__config__t.html", "structtopic__config__t" ],
    [ "topic_entry_t", "structtopic__entry__t.html", "structtopic__entry__t" ],
    [ "transition", "structtransition.html", "structtransition" ],
    [ "watchdog_obj_t", "structwatchdog__obj__t.html", "structwatchdog__obj__t" ]
];